version: '3.5'

services:
  db:
    container_name: tts_postgres_container_dev
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PWD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-dev_tts_db}
      PGDATA: /data/postgres
    ports:
      - "5433:5432"

  redis:
    container_name: tts_redis_container_dev
    image: redis
    ports:
      - "6378:6379"
networks:
  default:
    name: tts_network
