"""added first version of qa tables

Revision ID: 2d527a8b8fba
Revises: 3e06d1befa72
Create Date: 2023-04-03 19:20:30.294720

"""

# revision identifiers, used by Alembic.
revision = '2d527a8b8fba'
down_revision = '3e06d1befa72'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('s3url', sa.String(length=120), nullable=False),
    sa.Column('original_text', sa.String(length=120), nullable=False),
    sa.Column('asr_text', sa.String(length=120), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('sentence_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('s3url')
    )
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Approved', 'Rejected', name='status'), nullable=True),
    sa.Column('isAccentRight', sa.Boolean(), nullable=True),
    sa.Column('isPronunciationRight', sa.Boolean(), nullable=True),
    sa.Column('isTypeRight', sa.Boolean(), nullable=True),
    sa.Column('isClean', sa.Boolean(), nullable=True),
    sa.Column('isPausesRight', sa.Boolean(), nullable=True),
    sa.Column('isSpeedRight', sa.Boolean(), nullable=True),
    sa.Column('isConsisent', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotator.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation')
    op.drop_table('sample')
    op.drop_table('annotator')
    # ### end Alembic commands ###
