"""add root_cause table

Revision ID: 3e06d1befa72
Revises: 5ce68f0b1e77
Create Date: 2022-12-31 03:11:36.843111

"""

# revision identifiers, used by Alembic.
revision = "3e06d1befa72"
down_revision = "5ce68f0b1e77"
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_id",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_id")
    ### end Alembic commands ###
