"""small update

Revision ID: 3ef93bd496c8
Revises: 2d527a8b8fba
Create Date: 2023-04-03 21:27:24.764593

"""

# revision identifiers, used by Alembic.
revision = '3ef93bd496c8'
down_revision = '2d527a8b8fba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
