"""links added

Revision ID: 63c4c2d1c751
Revises: b03bfa7d16d2
Create Date: 2023-04-04 22:55:24.644846

"""

# revision identifiers, used by Alembic.
revision = '63c4c2d1c751'
down_revision = 'b03bfa7d16d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', 'email', name='_username_email_uc')
    )
    op.create_index(op.f('ix_annotator_id'), 'annotator', ['id'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='_name_uc')
    )
    op.create_index(op.f('ix_dataset_id'), 'dataset', ['id'], unique=False)
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('s3url', sa.String(length=120), nullable=False),
    sa.Column('original_text', sa.String(length=120), nullable=False),
    sa.Column('asr_text', sa.String(length=120), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('sentence_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filename', 's3url', name='_filename_s3url_uc'),
    sa.UniqueConstraint('s3url')
    )
    op.create_index(op.f('ix_sample_id'), 'sample', ['id'], unique=False)
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Approved', 'Rejected', name='status'), nullable=True),
    sa.Column('isAccentRight', sa.Boolean(), nullable=True),
    sa.Column('isPronunciationRight', sa.Boolean(), nullable=True),
    sa.Column('isTypeRight', sa.Boolean(), nullable=True),
    sa.Column('isClean', sa.Boolean(), nullable=True),
    sa.Column('isPausesRight', sa.Boolean(), nullable=True),
    sa.Column('isSpeedRight', sa.Boolean(), nullable=True),
    sa.Column('isConsisent', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotator.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotator_id', 'sample_id', name='_annotator_sample_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation')
    op.drop_index(op.f('ix_sample_id'), table_name='sample')
    op.drop_table('sample')
    op.drop_index(op.f('ix_dataset_id'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_annotator_id'), table_name='annotator')
    op.drop_table('annotator')
    # ### end Alembic commands ###
