"""add relationships

Revision ID: b03bfa7d16d2
Revises: 
Create Date: 2023-04-04 22:02:29.822271

"""

# revision identifiers, used by Alembic.
revision = 'b03bfa7d16d2'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', 'email', name='_username_email_uc')
    )
    op.create_index(op.f('ix_annotators_id'), 'annotators', ['id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='_name_uc')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('s3url', sa.String(length=120), nullable=False),
    sa.Column('original_text', sa.String(length=120), nullable=False),
    sa.Column('asr_text', sa.String(length=120), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('sentence_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filename', 's3url', name='_filename_s3url_uc'),
    sa.UniqueConstraint('s3url')
    )
    op.create_index(op.f('ix_samples_id'), 'samples', ['id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Approved', 'Rejected', name='status'), nullable=True),
    sa.Column('isAccentRight', sa.Boolean(), nullable=True),
    sa.Column('isPronunciationRight', sa.Boolean(), nullable=True),
    sa.Column('isTypeRight', sa.Boolean(), nullable=True),
    sa.Column('isClean', sa.Boolean(), nullable=True),
    sa.Column('isPausesRight', sa.Boolean(), nullable=True),
    sa.Column('isSpeedRight', sa.Boolean(), nullable=True),
    sa.Column('isConsisent', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotator_id', 'sample_id', name='_annotator_sample_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotations')
    op.drop_index(op.f('ix_samples_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_annotators_id'), table_name='annotators')
    op.drop_table('annotators')
    # ### end Alembic commands ###
